# CPAC Data Configuration File
# Version 1.6.1.a
#
# http://fcp-indi.github.io for more info.
#
# Tip: This file can be edited manually with a text editor for quick modifications.

- subject_id: s1
  unique_id: ses-1
  anat: /home/user/preproc-docs/cpac_sample_data/anat/s1_anat.nii.gz
  func:
    rest_1:
      scan: /home/user/preproc-docs/cpac_sample_data/func/s1_rest.nii.gz
  site: site-1



